words = [
        "Aftershaves",
    "Kettles",
    "Alarm clocks",
    "Kitchen Aids",
    "Badminton",
    "Knife Sets",
    "Bags Men",
    "Lego adults",
    "Barbie",
    "Lego kids",
    "Baskets",
    "Lighters",
    "Bathrobes",
    "Make up",
    "BBQ",
    "Miniature cars",
    "Binoculars",
    "Mugs",
    "Board Games",
    "Navigators",
    "Books Baking",
    "Party Accessories",
    "Books Biographies",
    "Penknives",
    "Books Cooking",
    "Perfumes",
    "Books Non-Fiction",
    "Plants",
    "Books Travel",
    "Playmobil",
    "Boxing",
    "Puzzles",
    "Camping Equipment",
    "Rucksacks",
    "Car Accessories",
    "Rugby",
    "Cat Accessories",
    "Running",
    "Chocolates",
    "Saucepan Sets",
    "Cleaning",
    "Shavers",
    "Coffee Machines",
    "Sport Bags",
    "Coffee Pots",
    "Stationary",
    "Computing Accessories",
    "Storage",
    "Cricket",
    "Sunglasses Men",
    "Cuddly Toys",
    "Sunglasses Women",
    "Cushions",
    "Swatch Watches",
    "Dinner Sets",
    "Swimming",
    "DIQ",
    "Teapots",
    "Dog Accessories",
    "Tennis",
    "Fishing",
    "Toaster",
    "Fitness",
    "Tooth brush",
    "Flowers",
    "Towels",
    "Football Merchandise",
    "Toys Boys",
    "Gaming",
    "Toys Girls",
    "Garden",
    "Travel Bags",
    "Gift Sets Men",
    "Travel Mugs",
    "Gift Sets Women",
    "Trimmers",
    "Glassware",
    "Umbrellas",
    "Golf",
    "Vases",
    "Hair Dryer",
    "Video Games",
    "Handbags",
    "Wallets Men",
    "Harley Davidson",
    "Wallets Women",
    "Headphones",
    "Water Bottles",
    "Jewellery",
    "Webcams",
    "Yoga"
]

import pandas as pd

pd.Series({
    "words":
    ["\n".join([part.capitalize() for part in word.split(" ")]) for word in words]
}).to_json("words.json", indent=4)
